// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfyhjiwgpxxyejpegyok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeWhqaXdncHh4eWVqcGVneW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzQ2MjksImV4cCI6MjA3MDAxMDYyOX0.UR6SWDHG6noEOE7jbBfaj-D3eBmZYdmnLt1rYD9rHCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});